#阿里云短信
aliyun:
  sms:
    regionId: cn-hangzhou
    keyId: LTAI4GGLCAbWjGCZn8tvfKMf
    keySecret: Cm6p5rx9WDJbEzw0mu7KCnuSueQabM
    templateCode: SMS_205457566
    signName: Mcsql在线教育

  vod:
    keyid: LTAI4G6VskXP7anbL6t4LCkY
    keysecret: dTYw1CUxOQmzf3016S4AcijtpOp2xd
    templateGroupId: null
    workflowId: null

# 顶象
dingxiang:
  sms:
    appId: f7789efe9697a602b53695a03f16a0ba
    appSecret: 960e99d8de614ee44f8b707c68ae6876
